
import json
from pathlib import Path

def get_api() -> dict:
    """
    Get openapi specification of the autogenerated part of the osparc client
    """
    return json.loads((Path(__file__).parent/'openapi.json').resolve().read_text())
