# coding: utf-8

"""
    Public API Server

    **osparc-simcore Public RESTful API Specifications** ## Python Library - Check the [documentation](https://itisfoundation.github.io/osparc-simcore-python-client) - Quick install: ``pip install git+https://github.com/ITISFoundation/osparc-simcore-python-client.git``   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from osparc.configuration import Configuration


class FileUploaded(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'filename': 'str',
        'content_type': 'str',
        'hash': 'str',
        'download_url': 'str'
    }

    attribute_map = {
        'filename': 'filename',
        'content_type': 'content_type',
        'hash': 'hash',
        'download_url': 'download_url'
    }

    def __init__(self, filename=None, content_type=None, hash=None, download_url=None, local_vars_configuration=None):  # noqa: E501
        """FileUploaded - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._filename = None
        self._content_type = None
        self._hash = None
        self._download_url = None
        self.discriminator = None

        self.filename = filename
        self.content_type = content_type
        self.hash = hash
        if download_url is not None:
            self.download_url = download_url

    @property
    def filename(self):
        """Gets the filename of this FileUploaded.  # noqa: E501


        :return: The filename of this FileUploaded.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this FileUploaded.


        :param filename: The filename of this FileUploaded.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and filename is None:  # noqa: E501
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def content_type(self):
        """Gets the content_type of this FileUploaded.  # noqa: E501


        :return: The content_type of this FileUploaded.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this FileUploaded.


        :param content_type: The content_type of this FileUploaded.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and content_type is None:  # noqa: E501
            raise ValueError("Invalid value for `content_type`, must not be `None`")  # noqa: E501

        self._content_type = content_type

    @property
    def hash(self):
        """Gets the hash of this FileUploaded.  # noqa: E501


        :return: The hash of this FileUploaded.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this FileUploaded.


        :param hash: The hash of this FileUploaded.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and hash is None:  # noqa: E501
            raise ValueError("Invalid value for `hash`, must not be `None`")  # noqa: E501

        self._hash = hash

    @property
    def download_url(self):
        """Gets the download_url of this FileUploaded.  # noqa: E501


        :return: The download_url of this FileUploaded.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this FileUploaded.


        :param download_url: The download_url of this FileUploaded.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                download_url is not None and len(download_url) > 2083):
            raise ValueError("Invalid value for `download_url`, length must be less than or equal to `2083`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                download_url is not None and len(download_url) < 1):
            raise ValueError("Invalid value for `download_url`, length must be greater than or equal to `1`")  # noqa: E501

        self._download_url = download_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileUploaded):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileUploaded):
            return True

        return self.to_dict() != other.to_dict()
