#
# SEE https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#
name: build-n-publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - staging_[a-zA-Z]+[0-9]+

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up latest Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Upgrade package tools
        run: >-
          python -m pip install -U
          pip
          setuptools
          wheel
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to *Test* PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
