name: python-client-artifact
run-name: python client
on:
  workflow_dispatch:
  push:
jobs:
  build-and-upload-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Generate client
        run: |
          make devenv
          source .venv/bin/activate
          cd clients/python
          make install-dev
          make dist-ci
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: osparc_python_client
          path: clients/python/artifacts/dist/
      - name: Publish distribution 📦 to *Test* PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
